### ISSUE TITLE
Entering entities in spectator mode results in being kicked from the server

### ISSUE THREAD

**Issue by Leomello** [2lstudios-mc/FlameCord#71] opened 2021-10-26 05:50 UTC
For me to be reporting this here is because I have checked everything possible to find the problem. Every time I enter an entity and press F5 to change the perspective of view, I get kicked off the server. This also happens to any other player who has access to this.

There are no errors in console, server, bungeecord and client. Only a screen of "ReadTimeoutException: null".

I tested this problem with the server outside the bungeecord and I don't get kicked, which makes it possible to be the flamecord/bungeecord with this problem.
I'm desperate for help as this affects my players.

Thanks.

[PRINT](https://prnt.sc/1xconp0)

PS: Death screen too.

**Comment by Leomello** [comment] 2021-10-30 21:32
I've already tried without plugins on bungeecord, and on spigot too and it's happening.
I used waterfall thinking it would stop, but the problem continued. This kick does not happen only if the spigot server is not linked to the bungeecord.
I've already tried to change my host's machine, and it also persisted.
That's why I'm coming to report to you because I don't know what else to do or try.

**Comment by Luccboy** [comment] 2021-10-30 22:39
Hi, I could recreate this issue with FlameCord 0.6.4 and Paper 1.16.5 (build 790). It seems to be a problem with FlameCord because this issue doesn't happen with Waterfall or BungeeCord. For some reason this problem doesn't appear in 1.8. But I could fix it by increasing the `timeout` value in FlameCord's config.yml to 20000 instead of 10000. (FlameCord sets the timeout to 10000 as a security measure, the default value in BungeeCord and Waterfall is 30000, that's probably the reason why the issue is only happening when using FlameCord) @Leomello Maybe you can also try to increase the timeout-value to ~20000 and write back wheter the problem persists or not :)

**Comment by Leomello** [comment] 2021-10-31 05:46
@Luccboy OMG! That really did. I never thought it was something harmless like that, I spent months with this problem. Thank you. i'm crying now ;-;

**Comment by Leomello** [comment] 2021-10-31 05:54
I had used the original Bungeecord and Waterfall in testing to find the problem, I didn't notice it was the timeout. Because when I ran the tests the configuration was 10000 because I didn't clean it. Honestly, I thought I was dumb at that.

**Comment by Luccboy** [comment] 2021-10-31 09:56
Great to hear that 😄

**Comment by linsaftw** [comment] 2021-10-31 14:17
fixed on c8ba018

**Closed by linsaftw** 2021-10-31 14:17 UTC
Labels: bug
